FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY services/notification/go.mod services/notification/go.sum ./
RUN go mod download

COPY services/notification ./services/notification

WORKDIR /app/services/notification
RUN go build -o /notification-consumer ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /notification-consumer .

CMD ["./notification-consumer"]